### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by smndvgnc** [tbriand/bspline_interpolation_c#1]
Good morning,
Is there a chance that the licence for this code (currently GPL2) could evolve to something less restrictive for industry applications, like LGPL for instance?
Regards.

**Comment by tbriand** [comment]
Hi,
Following your request we are going to modify the licence. A commit should be made soon.
Regards.

**Comment by smndvgnc** [comment]
Well thanks a lot!

**Comment by tbriand** [comment]
The licence has been modified.

**Comment by smndvgnc** [comment]
Very much appreciated, thank you. I'm closing the issue.
